### ISSUE TITLE
dip.corr_2d doesn't support correlation with 1D kernels.

### ISSUE THREAD

**Issue by Ris-Bali** [buddy-compiler/buddy-mlir#110]
**Describe the bug**

corr_2d op implemented in the DIP Dialect gives incorrect output for 1D kernels. For example kernels of the shape (n,1) or (1,n) where n is the number of elements.

**To Reproduce**

Steps to reproduce the behavior.
Test corr_2d with a 1D kernel an example could be [1, 2, 3] or any other kernel of shape (n, 1) or (1, n)

**Expected behavior**

OpenCV supports 1D kernels through filter2D. Currently, corr_2d is unable to support correlation with such 1D kernels.

**Screenshots**

![image](https://user-images.githubusercontent.com/81592570/215174610-65e839dc-230d-47e2-9e14-090e46a04447.png)

Here a (3,1) kernel is used (it can be observed the results of corr_2d (above) and filter2D do not match.

![image](https://user-images.githubusercontent.com/81592570/215175793-6582d4c7-8a85-4ef0-8490-08a40800d73a.png)

Here a (1,3) kernel is used and the observations are similar to the case above.

(In the above example the input image is of shape (5, 5) with the anchor at (0,0) and stride size of 2.

**Desktop (please complete the following information):**
 - OS: Pop OS (Ubuntu) 
 - Version: 22.04 LTS

**Additional context**

The corr_2d algorithm may require some changes to support 1D kernels; alternatively, a separate API for 1D convolutions can also be created.

**Comment by meshtag** [comment]
Can you specify the `stride` size which you used for generating these results.

**Comment by Ris-Bali** [comment]
Sorry, I have updated the PR initially I was using the default stride size of 128 I have now changed that to 2 and am getting similar error.
