### ISSUE TITLE
Example resize2D can not process images which have special resolution ratio

### ISSUE THREAD

**Issue by CBalaa** [buddy-compiler/buddy-mlir#124]
Example resize2D(path:examples/DIPDialect/resize2D.cpp) can not process images which have some special resolution ratio,such as 699*457, maybe there are some error codes in generated mlir. @meshtag 

My Desktop: Ubuntu22.04,  x86_64

**Comment by meshtag** [comment]
Thank you for reporting this issue! 
I'll investigate this when I get some time.

**Comment by CBalaa** [comment]
I can not find features of these sizes, I just can list some of them:  original size(width\*height): 699\*457;1920\*1700 ,and I only modify this part in `resize2D.cpp`:
```cpp
//  MemRef<float, 2> output = dip::Resize2D(
//      &input, dip::INTERPOLATION_TYPE::NEAREST_NEIGHBOUR_INTERPOLATION,
//      outputSize);
//   MemRef<float, 2> output = dip::Resize2D(
//       &input, dip::INTERPOLATION_TYPE::BILINEAR_INTERPOLATION, outputSize);

// MemRef<float, 2> output = dip::Resize2D(
//     &input, dip::INTERPOLATION_TYPE::NEAREST_NEIGHBOUR_INTERPOLATION,
//     scalingRatios);
   MemRef<float, 2> output = dip::Resize2D(
       &input, dip::INTERPOLATION_TYPE::BILINEAR_INTERPOLATION,
       scalingRatios);
```
So the `scalingRatios` and `outputSize` are all default(`scalingRatios = {4, 4}`, `outputSize[2] = {100, 250}`).

**Comment by CBalaa** [comment]
And different sizes may give different error message.

**Comment by CBalaa** [comment]
I can not find features of these sizes, I just can list some of them:  original size(width\*height): 699\*457;1920\*1700 ,and I only modify this part in `resize2D.cpp`:
```cpp
//  MemRef<float, 2> output = dip::Resize2D(
//      &input, dip::INTERPOLATION_TYPE::NEAREST_NEIGHBOUR_INTERPOLATION,
//      outputSize);
//   MemRef<float, 2> output = dip::Resize2D(
//       &input, dip::INTERPOLATION_TYPE::BILINEAR_INTERPOLATION, outputSize);

// MemRef<float, 2> output = dip::Resize2D(
//     &input, dip::INTERPOLATION_TYPE::NEAREST_NEIGHBOUR_INTERPOLATION,
//     scalingRatios);
   MemRef<float, 2> output = dip::Resize2D(
       &input, dip::INTERPOLATION_TYPE::BILINEAR_INTERPOLATION,
       scalingRatios);
```
So the `scalingRatios` and `outputSize` are all default(`scalingRatios = {4, 4}`, `outputSize[2] = {100, 250}`).

**Comment by meshtag** [comment]
You need to change the scaling ratios in accordance with the input size. Please refer [this comment](https://github.com/buddy-compiler/buddy-mlir/blob/c5c0075f0cad34efe66c64011626277c5fcab4d8/examples/DIPDialect/resize2D.cpp#L47).

**Comment by CBalaa** [comment]
I am not sure what that means.  Could you give me some examples?

**Comment by meshtag** [comment]
For Ex. if the original image's dimensions are {1000, 1000} and you want the output image dimensions to be {250, 250}, the scaling ratio input would be {Input_Image_Dim1/Output_Image_Dim1, Input_Image_Dim2/Output_Image_Dim2} i.e. {4, 4}

**Comment by meshtag** [comment]
> Do you mean that the image's size number should be an integral multiple of scale?
Nope.

Okay, this seems to be an issue with the `bilinear interpolation` implementation. Did you encounter these errors with `Nearest Neighbor interpolation` as well?

**Comment by meshtag** [comment]
I pushed some changes. Can you check if the issue is resolved now.

**Comment by CBalaa** [comment]
I didn't meet any errors in `Nearest Neighbor interpolation`. All issues have resolved now.
