### ISSUE TITLE
[build system] get rid of two-phase building

### ISSUE THREAD

**Issue by SharzyL** [buddy-compiler/buddy-mlir#132]
##### Is your feature request related to a problem? Please describe.

To build current version of buddy, two phases are required: first phase to build LLVM components, second phase to build buddy itself.

When trying to package buddy compiler with Nix, in my first attempt, I build LLVM as a separate package (or *derivation* in Nix jargon), then build buddy with `LLVM_DIR` and `MLIR_DIR` set to some path in the package installation directory. However, it failed to build buddy because what buddy requires is not only these installed files, but also some non-installed `cpp` files, even `include/llvm/Config/config.h`.

From the packager's perspective, the two-phase behavior and internal file dependency result in cumbersome and tricky packaging process (see https://github.com/sequencer/vector/blob/master/nix/buddy-mlir.nix#L34-L41). This is partially due to that Nix believes that **one** cmake will control everything. From a developer's perspective, the build manager (i.e. cmake) is not fully responsible for the state of the file tree. It will potentially cause cache inconsistency and portability issues.

##### Describe the solution you'd like

I propose two possible solutions:

1. Treat LLVM as a cmake submodule or subdirectory. One CMakeList.txt takes care of both LLVM and buddy build. I.e. build LLVM things into main build directory instead of into `llvm/build`. This might also reduce the total building time, because unused parts in LLVM will not be built.
2. Get rid of dependencies of LLVM internal files, use a installed LLVM tree. This makes things cleaner and perfect for packager. However, the developer requires more effort (execute `cmake --install` or something) unless first solution is applied.

I am not quite sure whether above two solutions will work, welcome for more suggestions.

**Comment by sequencer** [comment]
from the llvm doc [here](https://llvm.org/docs/CMake.html#id13)
> LLVM_EXTERNAL_PROJECTS:STRING
Semicolon-separated list of additional external projects to build as part of llvm. For each project LLVM_EXTERNAL_<NAME>_SOURCE_DIR have to be specified with the path for the source code of the project. Example: -DLLVM_EXTERNAL_PROJECTS="Foo;Bar" -DLLVM_EXTERNAL_FOO_SOURCE_DIR=/src/foo -DLLVM_EXTERNAL_BAR_SOURCE_DIR=/src/bar.

If depending on the uninstalled file in LLVM, maybe the better way is using `LLVM_EXTERNAL_PROJECTS`

**Comment by zhanghb97** [comment]
@SharzyL @sequencer Thanks for your suggestions, and sorry for the late reply!

There are two building strategies:

- Using `LLVM_EXTERNAL_PROJECTS`

- Using `LLVM_DIR` and `MLIR_DIR`

We are currently using the second approach, following the style of other MLIR-related projects, such as MLIR-HLO and CIRCT.

We'd love to add support for the one-step building strategy by using `LLVM_EXTERNAL_PROJECTS` to make our collaboration smooth. I will work to support this feature.

**Comment by zhanghb97** [comment]
> However, it failed to build buddy because what buddy requires is not only these installed files, but also some non-installed cpp files, even include/llvm/Config/config.h.

This is mainly because the Gemmini backend needs to add LLVM targets non-intrusively, so we use a tricky but work strategy that hybridizes some LLVM targets and buddy targets as the Gemmini backend.
