### ISSUE TITLE
Add caching mechanism for llvm build in GitHub Actions script

### ISSUE THREAD

**Issue by meshtag** [buddy-compiler/buddy-mlir#19]
**Is your feature request related to a problem? Please describe.**
GitHub actions builds are terribly slow due to the initiation of fresh llvm build process on each commit.

**Describe the solution you'd like**
We should cache the llvm build data daily (since we update llvm dependency daily). This would enable faster CI builds when multiple commits are pushed during the same day.

**Additional context**
Ref : https://github.com/buddy-compiler/buddy-mlir/blob/297956e034cc55262b2e97033e9a0d4fafbf495b/.github/workflows/TestBuild.yml#L12

Since this issue doesn't require any significant knowledge of codebase (GitHub actions knowledge will be required), I am marking it as a Good first issue.

**Comment by RishiKumarRay** [comment]
@meshtag will this work 
  - uses: actions/cache@v2
    with:
      path: | 
        path/to/dependencies
        some/other/dependencies 
      key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

**Comment by meshtag** [comment]
Thanks for your interest @RishiKumarRay !

> will this work

You can check it by adding a branch from your fork [here](https://github.com/buddy-compiler/buddy-mlir/blob/297956e034cc55262b2e97033e9a0d4fafbf495b/.github/workflows/TestBuild.yml#L5) .

Feel free to create a PR once your solution works :)

**Comment by RishiKumarRay** [comment]
@meshtag sure i will check this and raise pr

**Comment by ArtemSkrebkov** [comment]
Probably, can be closed after merging a PR #57

**Comment by zhanghb97** [comment]
Thanks @ArtemSkrebkov
