### ISSUE TITLE
The problem of `affine.parallel`

### ISSUE THREAD

**Issue by EllisLambda** [buddy-compiler/buddy-mlir#194]
**Is your feature request related to a problem? Please describe.**
Due to the difficulties in using `affine.parallel`, the outermost loop in the [BatchMatMulOptimize](https://github.com/EllisLambda/buddy-mlir/blob/b73ceb50041f0c9a0e198b21fdd756fe4c9afa17/midend/lib/Conversion/MatMulOptimization/BatchMatMulOptimize.cpp) of my PR does not utilize `affine.parallel`. However, this is crucial for the upcoming attempts to parallelize matmul using OpenMP. There's no open-source information available. I've tried writing code following the template, but it always results in errors

**Describe the solution you'd like**
Rewrite the outermost `affine.for` loop to `affine.parallel`

**Comment by xlinsist** [comment]
Maybe we should follow this topic. Could you provide some code demos to further illustrate the technical background and difficulties?

BTW Here are some suggestions when creating an issue that you may follow:
1. You can mention your PR by directly copying the link(whether it is from this repository or not) like this: https://github.com/buddy-compiler/buddy-benchmark/pull/73.
2. When you are seeking for a solution, try to avoid using ambiguous or unfocused naming of the title, make it spefific but not overly technical.

**Comment by EllisLambda** [comment]
The problem have been solved. Thanks for the advice!

**Comment by EllisLambda** [comment]
**The problem have been solved. Thanks for the advice!**
