### ISSUE TITLE
Add type inference mechanism in dip.corr_2d's lowering pass

### ISSUE THREAD

**Issue by meshtag** [buddy-compiler/buddy-mlir#21]
**Is your feature request related to a problem? Please describe.**
As of now, pixel elements are stored in a vector having floating point 32 bit elements while lowering dip.corr_2d (Ref : https://github.com/buddy-compiler/buddy-mlir/blob/0c427bde8824e5e004055eabe9b34d24933e0259/lib/Conversion/LowerDIP/LowerDIPPass.cpp#L165). 

**Describe the solution you'd like**
We should infer the type from user provided memref/image and use it for further calculations.

**Comment by ArtemSkrebkov** [comment]
Is it relevant?
I can take a look if it still makes sense

**Comment by meshtag** [comment]
> Is it relevant?

Yes
> I can take a look if it still makes sense

Alright

**Comment by ArtemSkrebkov** [comment]
I believe it can be closed.

**Comment by meshtag** [comment]
Related issue : https://github.com/buddy-compiler/buddy-mlir/issues/66
