### ISSUE TITLE
Segmentation fault while running examples/BuddyLamma/buddy-llama-run

### ISSUE THREAD

**Issue by jeff-ruby** [buddy-compiler/buddy-mlir#250]
**Describe the bug**
Just trial run the example buddy-llama-run for the first time, while generating the first output token by _mlir_ciface_forward(), segmentation fault happens. From the backstrace, it crashed at __memmove_avx_unaligned_erms()

**To Reproduce**
1. Build the code referred from the [README](https://github.com/buddy-compiler/buddy-mlir/blob/main/examples/BuddyLlama/README.md)
2. get and run the app at build/bin/buddy-llama-run
3. Segmentation fault happens

**Expected behavior**
Run outputs normally

**Screenshots**
Reading symbols from ./buddy-llama-run...
(gdb) r
Starting program: /home/code/buddy-mlir/build/bin/buddy-llama-run
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
LLaMA 2 Inference Powered by Buddy Compiler

Please send a message:
>>> How old are you?

[Log] Vocab file: "/home/code/buddy-mlir/examples/BuddyLlama/vocab.txt"
[Log] Tokenize time: 39.2032ms
[Log] Loading params...
[Log] Params file: "/home/code/buddy-mlir/examples/BuddyLlama/arg0.data"
[Log] Params load time: 37.844s

[New Thread 0x7ff385662b80 (LWP 216262)]
[New Thread 0x7ff384e60c00 (LWP 216263)]
[New Thread 0x7ff37fffec80 (LWP 216264)]
[New Thread 0x7ff37f7fcd00 (LWP 216265)]
[New Thread 0x7ff37effad80 (LWP 216266)]
[New Thread 0x7ff37e7f8e00 (LWP 216267)]
[New Thread 0x7ff37dff6e80 (LWP 216268)]
[New Thread 0x7ff37d7f4f00 (LWP 216269)]
[New Thread 0x7ff37cff2f80 (LWP 216270)]
[New Thread 0x7ff363fff000 (LWP 216271)]
[New Thread 0x7ff3637fd080 (LWP 216272)]
[New Thread 0x7ff362ffb100 (LWP 216273)]
[New Thread 0x7ff3627f9180 (LWP 216274)]
[New Thread 0x7ff361ff7200 (LWP 216275)]
[New Thread 0x7ff3617f5280 (LWP 216276)]
[New Thread 0x7ff360ff3300 (LWP 216277)]
[New Thread 0x7ff337fff380 (LWP 216278)]
[New Thread 0x7ff3377fd400 (LWP 216279)]
[New Thread 0x7ff336ffb480 (LWP 216280)]

Thread 1 "buddy-llama-run" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:262
262     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:262
#1  0x0000555555592d31 in forward ()
#2  0x00005555557c9103 in _mlir_ciface_forward ()
#3  0x0000555555559055 in main () at /home/oppo/code/buddy-mlir/examples/BuddyLlama/llama-main.cpp:155

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Additional context**

**Comment by zhanghb97** [comment]
Hi @jeff-ruby , thanks a lot for reporting this!
Could you please share your CPU details (e.g., `lscpu` output)? It'll help us trace and fix the issue more efficiently.
We will try to reproduce the crash and fix the potential bug.
Ping @weilinquan @weilinquan8 @xTayEx @Lester-1

**Comment by jeff-ruby** [comment]
> Hi @jeff-ruby , thanks a lot for reporting this! Could you please share your CPU details (e.g., `lscpu` output)? It'll help us trace and fix the issue more efficiently. We will try to reproduce the crash and fix the potential bug. Ping @weilinquan @weilinquan8 @xTayEx @Lester-1

Ok, the output of lscpu is:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      39 bits physical, 48 bits virtual
CPU(s):                             20
On-line CPU(s) list:                0-19
Thread(s) per core:                 2
Core(s) per socket:                 10
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              165
Model name:                         Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
Stepping:                           5
CPU MHz:                            3700.000
CPU max MHz:                        5300.0000
CPU min MHz:                        800.0000
BogoMIPS:                           7399.70
Virtualization:                     VT-x
L1d cache:                          320 KiB
L1i cache:                          320 KiB
L2 cache:                           2.5 MiB
L3 cache:                           20 MiB
NUMA node0 CPU(s):                  0-19
Vulnerability Gather data sampling: Mitigation; Microcode
Vulnerability Itlb multihit:        KVM: Mitigation: VMX disabled
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:             Mitigation; Enhanced IBRS
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Mitigation; Microcode
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch
                                    _perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_
                                    2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow
                                    vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida a
                                    rat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities

**Comment by weilinquan** [comment]
Hi, @jeff-ruby , Do you use OpenAI's opensoure llama2-7B model? If possible, Is it convenient for you to share your llama.mlir file?

**Comment by jeff-ruby** [comment]
> Hi, @jeff-ruby , Do you use OpenAI's opensoure llama2-7B model? If possible, Is it convenient for you to share your llama.mlir file? Thank you!

Hello weilingquan

I downloaded llama2-7B model from meta serveral months ago and converted it into HF format already before, so I did't use llama2-to-hf.py under examples/BuddyLlama. but I think it might be the same.

I am sorry the text of llama.mlir is too long and the company has the policy that the file should NOT be uploaded.

**Comment by weilinquan** [comment]
> > Hi, @jeff-ruby , Do you use OpenAI's opensoure llama2-7B model? If possible, Is it convenient for you to share your llama.mlir file? Thank you!
> 
> Hello weilingquan
> 
> I downloaded llama2-7B model from meta serveral months ago and converted it into HF format already before, so I did't use llama2-to-hf.py under examples/BuddyLlama. but I think it might be the same.
> 
> I am sorry the text of llama.mlir is too long and the company has the policy that the file should NOT be uploaded.

OK, How many output tensors in your llama.mlir? In our llama-main.cpp, we only support two output tensors now. And please check input tensors in your llama.mlir, there should also be two input tensors.

**Comment by weilinquan** [comment]
> > > > Hi, @jeff-ruby , Do you use OpenAI's opensoure llama2-7B model? If possible, Is it convenient for you to share your llama.mlir file? Thank you!
> > > 
> > > 
> > > Hello weilingquan
> > > I downloaded llama2-7B model from meta serveral months ago and converted it into HF format already before, so I did't use llama2-to-hf.py under examples/BuddyLlama. but I think it might be the same.
> > > I am sorry the text of llama.mlir is too long and the company has the policy that the file should NOT be uploaded.
> > 
> > 
> > OK, How many output tensors in your llama.mlir? In our llama-main.cpp, we only support two output tensors now. And please check input tensors in your llama.mlir, there should also be two input tensors. If possible, Is it convenient to share your llama.mlir's input and output tensors' shape?
> 
> Got it, the prototype of my llama.mlir is:
> 
> ```
> func.func @forward(%arg0: tensor<6771970048xf32>, %arg1: tensor<1x40xi64>) -> tensor<1x40x32000xf32>
> ```
> 
> seems that there is something mismatch with the number of output, I would try to convert and import it again.

Maybe you use out-date version of buddy-compiler, you can also try to update your buddy-compiler's version to newest.

**Comment by jeff-ruby** [comment]
@weilinquan @zhanghb97 

You have pointed the right problem.

I have pulled the latest code and tried again, the llama.mlir still have only 1 output: tensor<1x40x32000xf32>.
So I tried another way, just define 1 result tensor as below (and some related codes are skipped)
```code
MemRef<float, 3> resultContainer =
      MemRef<float, 3>({1, MaxTokenLength, MaxVocabSize}, false, 0);
```

then it works.

**Comment by xTayEx** [comment]
> @weilinquan @zhanghb97
> 
> You have pointed the right problem.
> 
> I have pulled the latest code and tried again, the llama.mlir still have only 1 output: tensor<1x40x32000xf32>. So I tried another way, just define 1 result tensor as below (and some related codes are skipped)
> 
> ```
> MemRef<float, 3> resultContainer =
>       MemRef<float, 3>({1, MaxTokenLength, MaxVocabSize}, false, 0);
> ```
> 
> then it works.

Hi jeff, have you deleted the old generated `llama.mlir`? Without removing it, `ninja` will think there is already a `llama.mlir` file, and the new (and correct) one will not be generated.

**Comment by jeff-ruby** [comment]
> > @weilinquan @zhanghb97
> > You have pointed the right problem.
> > I have pulled the latest code and tried again, the llama.mlir still have only 1 output: tensor<1x40x32000xf32>. So I tried another way, just define 1 result tensor as below (and some related codes are skipped)
> > ```
> > MemRef<float, 3> resultContainer =
> >       MemRef<float, 3>({1, MaxTokenLength, MaxVocabSize}, false, 0);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then it works.
> 
> Hi jeff, have you deleted the old generated `llama.mlir`? Without removing it, `ninja` will think there is already a `llama.mlir` file, and the new (and correct) one will not be generated.

Yes, I have deleted the old llama.mlir and re-generated the new one. Maybe there has subtle change between different versions of llama2(if there has). I have checked the llama2-7b-chat/LICENSE.txt, the realease data is as below: 
"Llama 2 Version Release Date: July 18, 2023"

**Comment by jeff-ruby** [comment]
> > @weilinquan @zhanghb97
> > You have pointed the right problem.
> > I have pulled the latest code and tried again, the llama.mlir still have only 1 output: tensor<1x40x32000xf32>. So I tried another way, just define 1 result tensor as below (and some related codes are skipped)
> > ```
> > MemRef<float, 3> resultContainer =
> >       MemRef<float, 3>({1, MaxTokenLength, MaxVocabSize}, false, 0);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then it works.
> 
> Hi jeff, have you deleted the old generated `llama.mlir`? Without removing it, `ninja` will think there is already a `llama.mlir` file, and the new (and correct) one will not be generated.

I pulled the latest codebase today(DEC 1) from the old version on NOV 27, then llama.mlir is as expected
