### ISSUE TITLE
The `torch` version used in `requirements.txt` seems to be removed

### ISSUE THREAD

**Issue by BHbean** [buddy-compiler/buddy-mlir#265]
**Describe the bug**
I am trying to reproduce the example under `examples/BuddyLlama`, but I found that the `torch` version used in `requirements.txt` seems to be removed.

**To Reproduce**
- Create a new conda env named `llama` and activate it
```bash
$ conda create -n llama
$ conda activate llama
```
-  Intall the packages needed
```bash
$ cd buddy-mlir
$ pip install -r requirements.txt
```
Then we can see the error.

**Expected behavior**
`torch` is successfully installed.

**Screenshots**
![image](https://github.com/buddy-compiler/buddy-mlir/assets/66934674/cc981d17-671c-497b-86f7-78c9c56f53ce)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Additional context**
I am trying another "dev" version of `torch`. However, for the sake of generality, maybe we should use a stable version of `torch` to make the reproduction of this example more stable?

**Comment by BHbean** [comment]
Besides, it seems that the `pybind11` package needs to be installed extraly by running `conda install pybind11 -c conda-forge` before building `llvm` and `buddy-mlir`, which will not be installed by running `pip install -r requirements.txt`.

**Comment by zhanghb97** [comment]
ping @Lester-1

**Comment by Lester-1** [comment]
Thank you for your suggestion. We have switched torch to a stable version. Please see the link https://github.com/buddy-compiler/buddy-mlir/pull/266 for details.

**Comment by zhanghb97** [comment]
@BHbean Thanks for reporting this! We have fixed the issue. Please check😄

**Comment by BHbean** [comment]
Thanks a lot! The `torch2.1.2+cpu` version did work!
> Besides, it seems that the `pybind11` package needs to be installed extraly by running `conda install pybind11 -c conda-forge` before building llvm and buddy-mlir, which will not be installed by running `pip install -r requirements.txt`.
Should this be added under `pip install -r requirements.txt` in `examples/BuddyLlama`? I could open a pr if you guys think it neccessary :)

**Comment by zhanghb97** [comment]
@BHbean, feel free to add this! Thanks!
