### ISSUE TITLE
Add `MemRef` container to buddy-mlir

### ISSUE THREAD

**Issue by zhanghb97** [buddy-compiler/buddy-mlir#27]

**Comment by zhanghb97** [comment]
The initial MemRef container and the test is [here](https://github.com/buddy-compiler/buddy-mlir/commit/78609761c7e8cec4488c7a75d3fe8d91e3a1e4ae).
The next step will add more tests and the derived class (image container).

**Comment by meshtag** [comment]
@zhanghb97 , do you think this issue can be closed?

**Comment by zhanghb97** [comment]
@meshtag Thanks!
