### ISSUE TITLE
cmake project falid

### ISSUE THREAD

**Issue by CXiaorong** [buddy-compiler/buddy-mlir#301]
# ​when rum this commard:
cmake -G Ninja .. \
    -DMLIR_DIR=$PWD/../llvm/build/lib/cmake/mlir \
    -DLLVM_DIR=$PWD/../llvm/build/lib/cmake/llvm \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DCMAKE_BUILD_TYPE=RELEASE

# Error:
CMake Error at llvm/build/lib/cmake/llvm/AddLLVM.cmake:612 (add_library):
Cannot find source file:

buddy-mlir-main/build/backend/llvm/lib/Target/RISCV/RISCVMacroFusion.cpp
Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
.hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
llvm/build/lib/cmake/llvm/AddLLVM.cmake:874 (llvm_add_library)
llvm/build/lib/cmake/llvm/AddLLVM.cmake:849 (add_llvm_library)
backend/llvm/lib/Target/RISCV/CMakeLists.txt:20 (add_llvm_component_library)
backend/llvm/lib/Target/RISCV/CMakeLists.txt:87 (buddy_add_llvm_target)

CMake Error at llvm/build/lib/cmake/llvm/AddLLVM.cmake:612 (add_library):
Cannot find source file:

buddy-mlir-main/llvm/llvm/lib/CodeGen/CodeGenPassBuilder.cpp

Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
.hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
llvm/build/lib/cmake/llvm/AddLLVM.cmake:874 (llvm_add_library)
llvm/build/lib/cmake/llvm/AddLLVM.cmake:849 (add_llvm_library)
backend/llvm/lib/CodeGen/CMakeLists.txt:3 (add_llvm_component_library)

CMake Error at llvm/build/lib/cmake/llvm/AddLLVM.cmake:612 (add_library):
Cannot find source file:

buddy-mlir-main/llvm/llvm/lib/Analysis/VFABIDemangling.cpp

​

**Comment by zhanghb97** [comment]
We are using llvm@[6c59f0e](https://github.com/llvm/llvm-project/tree/6c59f0e1b0fb56c909ad7c9aad4bde37dc006ae0) as our submodule. Please confirm that you are using the correct llvm version (head commit: [6c59f0e](https://github.com/llvm/llvm-project/tree/6c59f0e1b0fb56c909ad7c9aad4bde37dc006ae0))

**Comment by CXiaorong** [comment]
> We are using llvm@[6c59f0e](https://github.com/llvm/llvm-project/tree/6c59f0e1b0fb56c909ad7c9aad4bde37dc006ae0) as our submodule. Please confirm that you are using the correct llvm version (head commit: [6c59f0e](https://github.com/llvm/llvm-project/tree/6c59f0e1b0fb56c909ad7c9aad4bde37dc006ae0))

OK, the problem has been solved according to your steps, thank you very much.
