### ISSUE TITLE
Novel warning introduced due to usage of `Img<float, 2>` instead of `MemRef_descriptor` in `correlation2D.cpp`

### ISSUE THREAD

**Issue by meshtag** [buddy-compiler/buddy-mlir#48]
**Describe the bug**
The following warning is introduced when we use `Img<float, 2>` instead of `MemRef_descriptor` for the `input` variable in `correlation2D.cpp`.

```
root@3eb35749d59c:~/forks/buddy-mlir/build# ninja correlation2D
[1/2] Building CXX object examples/DIPDialect/CMakeFiles/correlation2D.dir/correlation2D.cpp.o
In file included from ../include/Interface/buddy/core/Container.h:88,
                 from ../include/Interface/buddy/core/ImageContainer.h:24,
                 from ../examples/DIPDialect/correlation2D.cpp:30:
../lib/Interface/core/Container.cpp: In function ‘bool testImplementation(int, char**, std::ptrdiff_t, std::ptrdiff_t, std::ptrdiff_t)’:
../lib/Interface/core/Container.cpp:164:3: warning: ‘input.Img<float, 2>::<anonymous>.MemRef<float, 2>::allocated’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  164 |   delete[] allocated;
      |   ^~~~~~
../examples/DIPDialect/correlation2D.cpp:106:17: note: ‘input.Img<float, 2>::<anonymous>.MemRef<float, 2>::allocated’ was declared here
  106 |   Img<float, 2> input(image);
      |                 ^~~~~
[2/2] Linking CXX executable bin/correlation2D
```

**To Reproduce**
Run `correlation2d.cpp` from [this](https://github.com/meshtag/buddy-mlir/tree/issue_warning_correlation2d) branch.

**Expected behavior**
Ideally, no new warning should be introduced due to porting of specialized container(s) in example(s).

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version : 20.04
 - Head commit of local llvm build : 0083a02839c3365af4b406042d35b82ded6b505c

**Additional context**
Continuation of discussion from [this](https://github.com/buddy-compiler/buddy-mlir/pull/23#issuecomment-1155984380) comment.

**Comment by zhanghb97** [comment]
@meshtag I can reproduce the warning for the correlation example, but I found that `edge-detection` example doesn't have the warning. Can you please try the `edge-detection` example to see if you can also trigger the warning for `edge-detection`. In principle, these two examples should be the same.

**Comment by meshtag** [comment]
@zhanghb97 , one solution is to initialize `allocated` and `aligned` with `NULL` [here](https://github.com/buddy-compiler/buddy-mlir/blob/4821614a4c9dc7a215d4daa38da8aeebd9b69782/include/Interface/buddy/core/Container.h#L76).
