### ISSUE TITLE
Bound check for operations with `memref`

### ISSUE THREAD

**Issue by Origami404** [buddy-compiler/buddy-mlir#87]
**Is your feature request related to a problem? Please describe.**

Currently, elements accessing operations on `memref` do not provide **any** bound check, which I think there should be some check. For example, even this example below can successfully pass lowering/translate/run:

```mlir
// Use global memref to ensure they are continuous in memory, for more 
// straight forward to show the result.
memref.global "private" @region_gv : memref<4xi32> = dense<[0, 1, 2, 3]>
memref.global "private" @canary_gv : memref<12xi32> = dense<202>
// 202 == 0xCA, means canary

func.func private @printMemrefI32(memref<*xi32>)

func.func @main() -> i32 {
  %region = memref.get_global @region_gv : memref<4xi32>
  %canary = memref.get_global @canary_gv : memref<12xi32>

  // ===================== test code ============================//
  %c1 = arith.constant 1 : i32
  %c5 = arith.constant 5 : index

  %region_print = memref.cast %region : memref<4xi32> to memref<*xi32>
  %canary_print = memref.cast %canary : memref<12xi32> to memref<*xi32>

  // NO ANY warning here! This type of access should be obvious for compiler.
  %val = memref.load %region[%c5] : memref<4xi32>
  vector.print %val : i32

  memref.store %c1, %region[%c5] : memref<4xi32>
  func.call @printMemrefI32(%region_print) : (memref<*xi32>) -> ()
  func.call @printMemrefI32(%canary_print) : (memref<*xi32>) -> ()

  %ret = arith.constant 0 : i32
  return %ret : i32
}
```

I have written [more examples](https://github.com/Origami404/buddy-mlir/tree/memref-oob-examples/examples/MLIRMemRefOutOfBound) for this problem on my forked repo.

**Describe the solution you'd like**

A warning should be given when trying to lower/translate/run files contains out of bound access when an analysis is possible.

**Describe alternatives you've considered**

AFAIK, there are three ways we can do better about this:

1. A pass may be added for bound checking. It seems easy to at least analyze the simplest cases (constant out-of-bound index for fixed length `memref`). And by keeping as long as the layout info inside or even between functions, we may also be possible to find out erased bound info like [this examples](https://github.com/Origami404/buddy-mlir/blob/memref-oob-examples/examples/MLIRMemRefOutOfBound/memref-oob-global.mlir). 
2. A pass to insert runtime bound check for every load/store or other operation on dynamic length `memref`. This is possible becasue striped layout dynamic length `memref` will be lowering with lengths in each dimension.
3. Just leave it over, and let LLVM or the lower-level compiler check this. They should be able to detect `gep` or pointer out-of-bound operations.

Option 1 seems great, but it may "reinvent the wheel" by re-implementing the common check which is usually done at LLVM IR level. Option 2 is very costly in runtime, but having such a mode in debugging seems great. Option 3 will delay the time that such errors are detected, and make it harder to map the error back to the source language. 

**Additional context**

Since most MLIR are created by compilers with higher level languages that may already ban unsafe memory operation, the bound check may be pushed up to be done before lowering to `memref` dialect or pushed down to be done after lowering to LLVM. The necessity of bound check in `memref` dialect level may need a deeper discussion.

In the current implement, the global `memref` will be continuous in memory, so it is the easiest way to see the effect of out-of-bound accesses. Stack allocated or normal memory allocated `memref` is not continuous in memory, which can be observed by reading `printMemRefI32`'s output by `mlir-cpu-runner`.

**Comment by meshtag** [comment]
I think this problem should be solved at its core i.e inside the `memref` dialect itself. Did you discuss this in official `mlir` forums? Changes related to core mlir dialects (like `memref` dialect) are out of scope for this project.

**Comment by meshtag** [comment]
@Origami404 , what is the status of this issue? Can we safely close it?

**Comment by Origami404** [comment]
No progress so far, can be closed now.
