### ISSUE TITLE
how to contact you in slack

### ISSUE THREAD

**Issue by leoluopy** [buddy-compiler/buddy-mlir#97]
I have downloaded slack, but i found that it's hard to join your group, especially i need a workspace url ，Is there any guide for us to join the slack workspace to contact you for some more details?
Or can we contact  in wechat group talk?

**Comment by leoluopy** [comment]
@zhanghb97 Have any idea?

**Comment by Origami404** [comment]
There is a invite link on [our website](https://buddy-compiler.github.io/), you may try [this](https://join.slack.com/t/buddycompiler/shared_invite/zt-13y6ibj4j-n6MQ8u9yCUPltCCDhLEmXg). It is at the bottom of page, so it's pretty easy to ignore it 😂.

If it doesn't work, please at me or zhanghb97.

**Comment by leoluopy** [comment]
![Screenshot_20221224_225146_com Slack](https://user-images.githubusercontent.com/9131273/209441484-40ef8fe8-af70-4288-b1b3-1479d4939b03.jpg)
